_keybase_secrets: 
  prod: "{{ lookup('file', '/keybase/team/cepro_cereal/secrets-prod.yml') | from_yaml }}"
  test: "{{ lookup('file', '/keybase/team/cepro_cereal/secrets-test.yml') | from_yaml }}"

keybase_secrets: "{{ _keybase_secrets.get(inventory_environment, None) }}"

cereal_host_subdomain: "{{ 'cereal.epfl.ch' if 'prod' in inventory_file else 'cereal-test.epfl.ch' }}"
crep_redirect_host_subdomain: "{{ 'crep.epfl.ch' if 'prod' in inventory_file else 'crep-test.epfl.ch' }}"
