- name: Ensure that CREP repository is present and up to date
  git:
    repo: 'https://github.com/epfl-cepro/crep'
    dest: /data/crep
    version: "main"
    force: yes

- name: "Copy env secrets from keybase ({{ inventory_mode }})"
  copy:
    src: "/keybase/team/cepro_crep/secrets-{{ inventory_mode }}.env"
    dest: /data/crep/.env
