- name: Ensure /etc/samba directory exists
  file: 
    path: "/etc/samba/"
    state: directory

- name: "Copy cifs credentials from keybase ({{ inventory_mode }})"
  copy:
    src: "/keybase/team/cepro_crep/cifs_creds"
    dest: /etc/samba/creds_crep_printing

- name: "Ensure CREP_PRINTING mounting directory exists"
  file: 
    path: "/mnt/CREP_PRINTING"
    state: directory

# Mounting SMB to /mnt/CREP_PRINTING, also putting this configuration into /etc/fstab so that it automatically mounts on restart.
- name: "Mount CREP_PRINTING SMB share"
  ansible.posix.mount:
    path: /mnt/CREP_PRINTING
    src: "{{ '//vpsi1files.epfl.ch/CAPE/TEST_CREP_EXAM' if inventory_environment == 'test' else '//vpsi1files.epfl.ch/repro_exam_printing' }}"
    fstype: cifs
    opts: credentials=/etc/samba/creds_crep_printing,iocharset=utf8,vers=3.0,_netdev
    state: mounted

- name: Create Docker network
  ansible.builtin.docker_network:
    name: crep-network

- name: Build CREP image
  community.docker.docker_image:
    name: crep
    source: build
    force_source: yes
    build:
      path: /data/crep

- name: Create Docker CREP
  ansible.builtin.docker_container:
    name: crep-app
    image: crep
    state: started
    ports:
      - "3000:3000"
    networks:
      - name: crep-network
        aliases:
          - nextjs
    env:
      NODE_ENV: production
      CREP_ENV: "{{ inventory_environment }}"
    env_file: /data/crep/.env
    # /mnt/CREP_PRINTING is mounted inside the container, also with the path /mnt/CREP_PRINTING
    volumes:
      - /mnt/CREP_PRINTING:/mnt/CREP_PRINTING:rw
