- include_tasks:
    file: setup.yml
    apply:
      tags:
        - cereal.setup
  tags: always

- include_tasks:
    file: repository.yml
    apply:
      tags:
        - cereal.repository
  tags: always

- include_tasks:
    file: database.yml
    apply:
      tags:
        - cereal.database
  tags: always

- include_tasks:
    file: run.yml
    apply:
      tags:
        - cereal.run
  tags: always

- include_tasks:
    file: apache.yml
    apply:
      tags:
        - cereal.apache
  tags: always
